universities = [
  { name: 'Universidad Nacional' },
  { name: 'Universidad de los Andes' },
  { name: 'Universidad Javeriana' },
  { name: 'Universidad Libre' },
  { name: 'Escuela Colombiana de Ingeniería Julio Garavito' },
  { name: 'Universidad Sergio Arboleda' },
  { name: 'Universidad Jorge Tadeo Lozano' },
  { name: 'Fundación Universidad de América' },
  { name: 'Universidad Santo Tomás' },
  { name: 'Universidad Manuela Beltrán' },
  { name: 'Universidad Distrital Francisco José de Caldas' },
  { name: 'Universidad de la Salle Norte' },
  { name: 'Universidad de la Salle Centro' },
  { name: 'Universidad de la Salle Chapinero' },
  { name: 'Universidad Central Centro' },
  { name: 'Universidad Central Norte' },
  { name: 'Universidad del Rosario' },
  { name: 'Universidad Católica de Colombia' },
  { name: 'Universidad El Bosque' },
  { name: 'Fundación Universitaria Los Libertadores' },
  { name: 'Universidad Distrital Francisco José de Caldas' },
  { name: 'Universidad Externado' },
  { name: 'Universidad Militar Nueva Granada'},
  { name: 'Fundación Universitaria Konrad Lorenz' },
  { name: 'Universidad Piloto de Colombia'},
  { name: 'Universidad Incca de Colombia'},
  { name: 'Universidad Autónoma de Colombia'},
  { name: 'Universidad Pedagógica Nacional'},
  { name: 'Fundación Universitaria San Martín'},
  { name: 'Colegio de Estudios Superiores de Administración'},
  { name: 'Universidad San Buenaventura'},
  { name: 'Universidad de la Sabana'}
]
University.create!(universities)
