universities = [
  { name: 'Universidad Nacional', address: 'Carrera 30 #45-05' },
  { name: 'Universidad de los Andes', address: 'Cra 1 #18A-12' },
  { name: 'Universidad Javeriana', address: 'Carrera 7 #40-62' },
  { name: 'Universidad Libre', address: 'Calle 8a #5-80' },
  { name: 'Escuela Colombiana de Ingeniería Julio Garavito', address: 'Carrera 45 #205-59' },
  { name: 'Universidad Sergio Arboleda', address: 'Calle 74 #14-14' },
  { name: 'Universidad Jorge Tadeo Lozano', address: 'Carrera 4 #22-61' },
  { name: 'Fundación Universidad de América', address: 'Avenida Circunvalar #20-53' },
  { name: 'Universidad Santo Tomás', address: 'Carrera 9 #51 - 11' },
  { name: 'Universidad Manuela Beltrán', address: 'Avenida Circunvalar #60-00' },
  { name: 'Universidad Distrital Francisco José de Caldas', address: 'Carrera 7 #40B - 53' },
  { name: 'Universidad de la Salle Norte', address: 'Carrera 7 #172-85' },
  { name: 'Universidad de la Salle Centro', address: 'Carrera 2 #10-70' },
  { name: 'Universidad de la Salle Chapinero', address: 'Cra. 5 #59A-44' },
  { name: 'Universidad Central Centro', address: 'Calle 21 #4-40' },
  { name: 'Universidad Central Norte', address: 'calle 75 #16-03' },
  { name: 'Universidad del Rosario', address: 'Calle 12C #6-25' },
  { name: 'Universidad Católica de Colombia', address: 'Avenida Caracas #46 -72' },
  { name: 'Universidad El Bosque', address: 'Avenida Carrera 9 #131 A-02' },
  { name: 'Fundación Universitaria Los Libertadores', address: 'Carrera 16 #63 A-68' },
  { name: 'Universidad Distrital Francisco José de Caldas', address: 'Carrera 7 #40B - 53'},
  { name: 'Universidad Externado', address: 'Calle 12 #1-17 Este'},
  { name: 'Universidad Militar Nueva Granada', address: 'Carrera 11 #101-80 '},
  { name: 'Fundación Universitaria Konrad Lorenz', address: 'Carrera 9 Bis #62-43'},
  { name: 'Universidad Piloto de Colombia', address: 'Carrera 9 #45A-44'},
  { name: 'Universidad Incca de Colombia', address: 'Carrera 13 #24-15 '},
  { name: 'Universidad Autónoma de Colombia', address: 'Calle 12B #4-31'},
  { name: 'Universidad Pedagógica Nacional', address: 'Calle 72 #11-86'},
  { name: 'Fundación Universitaria San Martín', address: 'Carrera 18#80-45'},
  { name: 'Colegio de Estudios Superiores de Administración', address: 'Cra. 6 #34-51'},
  { name: 'Universidad San Buenaventura', address: 'Carrera 8H #172-20'}
]
University.create!(universities)